title: Woohoo
author: GitHub User
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  I hope this works......
theme: minima

# social links
twitter_username: aryandugar2 # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
